### ISSUE TITLE
Problem importing all resources

### ISSUE THREAD

**Issue by davidkaste** [rhizomik/rhizomer#3]
In some "Classes", inserts the same instance more than once. ('-1' SHA1 hash ending)

**Comment by rogargon** [comment]
Try this query, it seems to work with Marmotta:

SELECT DISTINCT ?i ?class
WHERE { 
  ?i a ?class
  FILTER NOT EXISTS { 
    ?i a ?class2. ?class2 rdfs:subClassOf ?class.
    FILTER (?class!=?class2) }
} ORDER BY ?i ?class

**Comment by davidkaste** [comment]
I believe that this error is an implementation problem and it has nothing to do with this query. I need to check if every generated URL exists in Marmotta LDP. If it exists, I don't need to reinsert the requested resource.
